import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  CreditCard,
  DollarSign,
  FileText,
  Grid3X3,
  Heart,
  ImagePlus,
  LayoutDashboard,
  List,
  Loader2,
  Lock,
  LogOut,
  Menu,
  Minus,
  Package,
  Plus,
  RotateCcw as RotateCounterClockwise,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Store,
  TrendingUp,
  Trash2,
  Truck,
  User,
  X,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  dollarSign: DollarSign,
  fileText: FileText,
  grid3X3: Grid3X3,
  heart: Heart,
  imagePlus: ImagePlus,
  layoutDashboard: LayoutDashboard,
  list: List,
  loader: Loader2,
  lock: Lock,
  logOut: LogOut,
  menu: Menu,
  minus: Minus,
  package: Package,
  plus: Plus,
  rotateCounterClockwise: RotateCounterClockwise,
  search: Search,
  settings: Settings,
  shield: Shield,
  shoppingCart: ShoppingCart,
  spinner: Loader2,
  star: Star,
  store: Store,
  trash2: Trash2,
  trendingUp: TrendingUp,
  truck: Truck,
  user: User,
  x: X,
};